server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization?serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: none
      
logging:
  level:
    org:
      hibernate:
        type: trace
        
security:
  oauth2:
     resource:
        token-info-uri: http://localhost:9090/oauth/check_token
     client:      
        client-id: mobile
        client-secret: pin 